#!/bin/bash
set -e
if [ $# != 1 ]
then
	echo usage: $0 rulesetname
  exit 1
fi
mkdir -p target/classes
java -cp $(echo target/dependency/*|sed 's/ /:/g') net.sf.saxon.Transform -s:src/main/resources/$1.xml\
 -xsl:xslt/workbenchToRules.xslt\
 -o:target/classes/$1.xml\
 +description=$(realpath src/main/resources/$(basename $1 .xml).description)
