#!/bin/bash
set -xe
for i in src/main/pmd/*.appstate
do
	tools/convertToRuleFile.sh $(basename $i .appstate)
done
for i in src/main/pmd/*.xml
do
	cp $i target/classes
done
cp target/classes/*.xml target
